# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1140ad6d9e1e3b88db3d7f35180f30bea4fa15bfd425a1834850e71eba8a205059c04564c712dd198d0e93dc29b8808cf5b28e5dc2377f522b7844d84380d0fb

test:
  secret_key_base: 0ae21ad105fa1af808334a0e73f8da55390e33cabb14929843efba7663fec7dc90b7338e644c892bffa94917c72260c87506dcbfce6846dd86d2ec0e63106431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
